// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: vortex/v1/node.proto

package genv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_Sync_FullMethodName          = "/vortex.v1.NodeService/Sync"
	NodeService_AddUser_FullMethodName       = "/vortex.v1.NodeService/AddUser"
	NodeService_RemoveUser_FullMethodName    = "/vortex.v1.NodeService/RemoveUser"
	NodeService_StreamTraffic_FullMethodName = "/vortex.v1.NodeService/StreamTraffic"
	NodeService_Health_FullMethodName        = "/vortex.v1.NodeService/Health"
	NodeService_RestartCore_FullMethodName   = "/vortex.v1.NodeService/RestartCore"
	NodeService_StopCore_FullMethodName      = "/vortex.v1.NodeService/StopCore"
	NodeService_OnlineStats_FullMethodName   = "/vortex.v1.NodeService/OnlineStats"
	NodeService_NodeLogs_FullMethodName      = "/vortex.v1.NodeService/NodeLogs"
	NodeService_OnlineIPs_FullMethodName     = "/vortex.v1.NodeService/OnlineIPs"
	NodeService_UpdateGeo_FullMethodName     = "/vortex.v1.NodeService/UpdateGeo"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeService is served by the node agent. The panel is the gRPC client and
// dials each node over mTLS. Mutating RPCs are unary; traffic accounting uses a
// long-lived server stream so the node *pushes* deltas instead of being polled.
type NodeServiceClient interface {
	// Sync replaces the node's entire desired state (inbounds + user bindings).
	// Used on (re)connect and after bulk changes; idempotent.
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*Ack, error)
	// AddUser provisions one user on one inbound at runtime (no core restart).
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*Ack, error)
	// RemoveUser deprovisions one user from one inbound at runtime.
	RemoveUser(ctx context.Context, in *RemoveUserRequest, opts ...grpc.CallOption) (*Ack, error)
	// StreamTraffic is opened once by the panel and stays open; the node emits a
	// TrafficDelta whenever it has accounted usage. Deltas are incremental, so the
	// panel sums them idempotently and restarts never double count.
	StreamTraffic(ctx context.Context, in *StreamTrafficRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrafficDelta], error)
	// Health returns a live resource/liveness snapshot for failover decisions.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// RestartCore restarts the proxy engine process (applies latest config).
	RestartCore(ctx context.Context, in *RestartCoreRequest, opts ...grpc.CallOption) (*Ack, error)
	// StopCore gracefully shuts the proxy engine down.
	StopCore(ctx context.Context, in *StopCoreRequest, opts ...grpc.CallOption) (*Ack, error)
	// OnlineStats returns the current live-connection count per user (keyed by the
	// user's stats email == UUID). Polled on demand by the panel.
	OnlineStats(ctx context.Context, in *OnlineStatsRequest, opts ...grpc.CallOption) (*OnlineStatsResponse, error)
	// NodeLogs returns the most recent core log lines captured by the agent.
	NodeLogs(ctx context.Context, in *NodeLogsRequest, opts ...grpc.CallOption) (*NodeLogsResponse, error)
	// OnlineIPs returns the distinct source IPs currently online for one user
	// (keyed by user stats email == UUID), with each IP's last-seen unix time.
	// Used to detect account sharing. Empty when the engine cannot report it.
	OnlineIPs(ctx context.Context, in *OnlineIPsRequest, opts ...grpc.CallOption) (*OnlineIPsResponse, error)
	// UpdateGeo downloads geoip/geosite routing databases into the engine's asset
	// directory and reloads. Used to refresh country/domain routing data (e.g.
	// Iran rules) without a full redeploy.
	UpdateGeo(ctx context.Context, in *UpdateGeoRequest, opts ...grpc.CallOption) (*UpdateGeoResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, NodeService_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, NodeService_AddUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RemoveUser(ctx context.Context, in *RemoveUserRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, NodeService_RemoveUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StreamTraffic(ctx context.Context, in *StreamTrafficRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrafficDelta], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_StreamTraffic_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamTrafficRequest, TrafficDelta]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamTrafficClient = grpc.ServerStreamingClient[TrafficDelta]

func (c *nodeServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, NodeService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RestartCore(ctx context.Context, in *RestartCoreRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, NodeService_RestartCore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StopCore(ctx context.Context, in *StopCoreRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, NodeService_StopCore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) OnlineStats(ctx context.Context, in *OnlineStatsRequest, opts ...grpc.CallOption) (*OnlineStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnlineStatsResponse)
	err := c.cc.Invoke(ctx, NodeService_OnlineStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) NodeLogs(ctx context.Context, in *NodeLogsRequest, opts ...grpc.CallOption) (*NodeLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeLogsResponse)
	err := c.cc.Invoke(ctx, NodeService_NodeLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) OnlineIPs(ctx context.Context, in *OnlineIPsRequest, opts ...grpc.CallOption) (*OnlineIPsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnlineIPsResponse)
	err := c.cc.Invoke(ctx, NodeService_OnlineIPs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) UpdateGeo(ctx context.Context, in *UpdateGeoRequest, opts ...grpc.CallOption) (*UpdateGeoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGeoResponse)
	err := c.cc.Invoke(ctx, NodeService_UpdateGeo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
//
// NodeService is served by the node agent. The panel is the gRPC client and
// dials each node over mTLS. Mutating RPCs are unary; traffic accounting uses a
// long-lived server stream so the node *pushes* deltas instead of being polled.
type NodeServiceServer interface {
	// Sync replaces the node's entire desired state (inbounds + user bindings).
	// Used on (re)connect and after bulk changes; idempotent.
	Sync(context.Context, *SyncRequest) (*Ack, error)
	// AddUser provisions one user on one inbound at runtime (no core restart).
	AddUser(context.Context, *AddUserRequest) (*Ack, error)
	// RemoveUser deprovisions one user from one inbound at runtime.
	RemoveUser(context.Context, *RemoveUserRequest) (*Ack, error)
	// StreamTraffic is opened once by the panel and stays open; the node emits a
	// TrafficDelta whenever it has accounted usage. Deltas are incremental, so the
	// panel sums them idempotently and restarts never double count.
	StreamTraffic(*StreamTrafficRequest, grpc.ServerStreamingServer[TrafficDelta]) error
	// Health returns a live resource/liveness snapshot for failover decisions.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// RestartCore restarts the proxy engine process (applies latest config).
	RestartCore(context.Context, *RestartCoreRequest) (*Ack, error)
	// StopCore gracefully shuts the proxy engine down.
	StopCore(context.Context, *StopCoreRequest) (*Ack, error)
	// OnlineStats returns the current live-connection count per user (keyed by the
	// user's stats email == UUID). Polled on demand by the panel.
	OnlineStats(context.Context, *OnlineStatsRequest) (*OnlineStatsResponse, error)
	// NodeLogs returns the most recent core log lines captured by the agent.
	NodeLogs(context.Context, *NodeLogsRequest) (*NodeLogsResponse, error)
	// OnlineIPs returns the distinct source IPs currently online for one user
	// (keyed by user stats email == UUID), with each IP's last-seen unix time.
	// Used to detect account sharing. Empty when the engine cannot report it.
	OnlineIPs(context.Context, *OnlineIPsRequest) (*OnlineIPsResponse, error)
	// UpdateGeo downloads geoip/geosite routing databases into the engine's asset
	// directory and reloads. Used to refresh country/domain routing data (e.g.
	// Iran rules) without a full redeploy.
	UpdateGeo(context.Context, *UpdateGeoRequest) (*UpdateGeoResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) Sync(context.Context, *SyncRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedNodeServiceServer) AddUser(context.Context, *AddUserRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedNodeServiceServer) RemoveUser(context.Context, *RemoveUserRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUser not implemented")
}
func (UnimplementedNodeServiceServer) StreamTraffic(*StreamTrafficRequest, grpc.ServerStreamingServer[TrafficDelta]) error {
	return status.Error(codes.Unimplemented, "method StreamTraffic not implemented")
}
func (UnimplementedNodeServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedNodeServiceServer) RestartCore(context.Context, *RestartCoreRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartCore not implemented")
}
func (UnimplementedNodeServiceServer) StopCore(context.Context, *StopCoreRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method StopCore not implemented")
}
func (UnimplementedNodeServiceServer) OnlineStats(context.Context, *OnlineStatsRequest) (*OnlineStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnlineStats not implemented")
}
func (UnimplementedNodeServiceServer) NodeLogs(context.Context, *NodeLogsRequest) (*NodeLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeLogs not implemented")
}
func (UnimplementedNodeServiceServer) OnlineIPs(context.Context, *OnlineIPsRequest) (*OnlineIPsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnlineIPs not implemented")
}
func (UnimplementedNodeServiceServer) UpdateGeo(context.Context, *UpdateGeoRequest) (*UpdateGeoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGeo not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_AddUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RemoveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RemoveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RemoveUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RemoveUser(ctx, req.(*RemoveUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StreamTraffic_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTrafficRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).StreamTraffic(m, &grpc.GenericServerStream[StreamTrafficRequest, TrafficDelta]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamTrafficServer = grpc.ServerStreamingServer[TrafficDelta]

func _NodeService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RestartCore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartCoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RestartCore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RestartCore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RestartCore(ctx, req.(*RestartCoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StopCore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopCoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).StopCore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_StopCore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).StopCore(ctx, req.(*StopCoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_OnlineStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).OnlineStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_OnlineStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).OnlineStats(ctx, req.(*OnlineStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_NodeLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).NodeLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_NodeLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).NodeLogs(ctx, req.(*NodeLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_OnlineIPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineIPsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).OnlineIPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_OnlineIPs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).OnlineIPs(ctx, req.(*OnlineIPsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_UpdateGeo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGeoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).UpdateGeo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_UpdateGeo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).UpdateGeo(ctx, req.(*UpdateGeoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vortex.v1.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _NodeService_Sync_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _NodeService_AddUser_Handler,
		},
		{
			MethodName: "RemoveUser",
			Handler:    _NodeService_RemoveUser_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _NodeService_Health_Handler,
		},
		{
			MethodName: "RestartCore",
			Handler:    _NodeService_RestartCore_Handler,
		},
		{
			MethodName: "StopCore",
			Handler:    _NodeService_StopCore_Handler,
		},
		{
			MethodName: "OnlineStats",
			Handler:    _NodeService_OnlineStats_Handler,
		},
		{
			MethodName: "NodeLogs",
			Handler:    _NodeService_NodeLogs_Handler,
		},
		{
			MethodName: "OnlineIPs",
			Handler:    _NodeService_OnlineIPs_Handler,
		},
		{
			MethodName: "UpdateGeo",
			Handler:    _NodeService_UpdateGeo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTraffic",
			Handler:       _NodeService_StreamTraffic_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vortex/v1/node.proto",
}
