// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vortex/v1/node.proto

package genv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoreType int32

const (
	CoreType_CORE_TYPE_UNSPECIFIED CoreType = 0
	CoreType_CORE_TYPE_XRAY        CoreType = 1
	CoreType_CORE_TYPE_SINGBOX     CoreType = 2
)

// Enum value maps for CoreType.
var (
	CoreType_name = map[int32]string{
		0: "CORE_TYPE_UNSPECIFIED",
		1: "CORE_TYPE_XRAY",
		2: "CORE_TYPE_SINGBOX",
	}
	CoreType_value = map[string]int32{
		"CORE_TYPE_UNSPECIFIED": 0,
		"CORE_TYPE_XRAY":        1,
		"CORE_TYPE_SINGBOX":     2,
	}
)

func (x CoreType) Enum() *CoreType {
	p := new(CoreType)
	*p = x
	return p
}

func (x CoreType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoreType) Descriptor() protoreflect.EnumDescriptor {
	return file_vortex_v1_node_proto_enumTypes[0].Descriptor()
}

func (CoreType) Type() protoreflect.EnumType {
	return &file_vortex_v1_node_proto_enumTypes[0]
}

func (x CoreType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoreType.Descriptor instead.
func (CoreType) EnumDescriptor() ([]byte, []int) {
	return file_vortex_v1_node_proto_rawDescGZIP(), []int{0}
}

// UserSpec is the minimal, engine-neutral identity the core needs to admit a
// user on an inbound. Secrets are reused across protocols by the panel.
type UserSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // canonical UUID
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                 // core "email"/tag, used as the stats key
	VmessUuid      string                 `protobuf:"bytes,3,opt,name=vmess_uuid,json=vmessUuid,proto3" json:"vmess_uuid,omitempty"`
	VlessUuid      string                 `protobuf:"bytes,4,opt,name=vless_uuid,json=vlessUuid,proto3" json:"vless_uuid,omitempty"`
	TrojanPassword string                 `protobuf:"bytes,5,opt,name=trojan_password,json=trojanPassword,proto3" json:"trojan_password,omitempty"`
	SsPassword     string                 `protobuf:"bytes,6,opt,name=ss_password,json=ssPassword,proto3" json:"ss_password,omitempty"`
	SsMethod       string                 `protobuf:"bytes,7,opt,name=ss_method,json=ssMethod,proto3" json:"ss_method,omitempty"`
	Flow           string                 `protobuf:"bytes,8,opt,name=flow,proto3" json:"flow,omitempty"` // e.g. xtls-rprx-vision
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserSpec) Reset() {
	*x = UserSpec{}
	mi := &file_vortex_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSpec) ProtoMessage() {}

func (x *UserSpec) ProtoReflect() protoreflect.Message {
	mi := &file_vortex_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSpec.ProtoReflect.Descriptor instead.
func (*UserSpec) Descriptor() ([]byte, []int) {
	return file_vortex_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *UserSpec) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSpec) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSpec) GetVmessUuid() string {
	if x != nil {
		return x.VmessUuid
	}
	return ""
}

func (x *UserSpec) GetVlessUuid() string {
	if x != nil {
		return x.VlessUuid
	}
	return ""
}

func (x *UserSpec) GetTrojanPassword() string {
	if x != nil {
		return x.TrojanPassword
	}
	return ""
}

func (x *UserSpec) GetSsPassword() string {
	if x != nil {
		return x.SsPassword
	}
	return ""
}

func (x *UserSpec) GetSsMethod() string {
	if x != nil {
		return x.SsMethod
	}
	return ""
}

func (x *UserSpec) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

// InboundSpec is the rendered inbound the node should be listening on. Raw holds
// engine-native JSON overrides for fields not modeled by the abstraction.
type InboundSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Listen        string                 `protobuf:"bytes,3,opt,name=listen,proto3" json:"listen,omitempty"`
	Port          uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Network       string                 `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	Security      string                 `protobuf:"bytes,6,opt,name=security,proto3" json:"security,omitempty"`
	Raw           []byte                 `protobuf:"bytes,7,opt,name=raw,proto3" json:"raw,omitempty"` // optional native JSON fragment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundSpec) Reset() {
	*x = InboundSpec{}
	mi := &file_vortex_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundSpec) ProtoMessage() {}

func (x *InboundSpec) ProtoReflect() protoreflect.Message {
	mi := &file_vortex_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundSpec.ProtoReflect.Descriptor instead.
func (*InboundSpec) Descriptor() ([]byte, []int) {
	return file_vortex_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *InboundSpec) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *InboundSpec) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *InboundSpec) GetListen() string {
	if x != nil {
		return x.Listen
	}
	return ""
}

func (x *InboundSpec) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *InboundSpec) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *InboundSpec) GetSecurity() string {
	if x != nil {
		return x.Security
	}
	return ""
}

func (x *InboundSpec) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type SyncRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Core     CoreType               `protobuf:"varint,1,opt,name=core,proto3,enum=vortex.v1.CoreType" json:"core,omitempty"`
	LogLevel string                 `protobuf:"bytes,2,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	Inbounds []*InboundSpec         `protobuf:"bytes,3,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	// users_by_inbound maps inbound tag -> users bound to it.
	UsersByInbound map[string]*UserList `protobuf:"bytes,4,rep,name=users_by_inbound,json=usersByInbound,proto3" json:"users_by_inbound,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_vortex_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vortex_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_vortex_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *SyncRequest) GetCore() CoreType {
	if x != nil {
		return x.Core
	}
	return CoreType_CORE_TYPE_UNSPECIFIED
}

func (x *SyncRequest) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *SyncRequest) GetInbounds() []*InboundSpec {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

func (x *SyncRequest) GetUsersByInbound() map[string]*UserList {
	if x != nil {
		return x.UsersByInbound
	}
	return nil
}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserSpec            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_vortex_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_vortex_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_vortex_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *UserList) GetUsers() []*UserSpec {
	if x != nil {
		return x.Users
	}
	return nil
}

type AddUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InboundTag    string                 `protobuf:"bytes,1,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	User          *UserSpec              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	mi := &file_vortex_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vortex_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_vortex_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *AddUserRequest) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *AddUserRequest) GetUser() *UserSpec {
	if x != nil {
		return x.User
	}
	return nil
}

type RemoveUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InboundTag    string                 `protobuf:"bytes,1,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRequest) Reset() {
	*x = RemoveUserRequest{}
	mi := &file_vortex_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRequest) ProtoMessage() {}

func (x *RemoveUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vortex_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserRequest) Descriptor() ([]byte, []int) {
	return file_vortex_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveUserRequest) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *RemoveUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type StreamTrafficRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// min_report_interval_ms lets the panel cap how chatty the stream is; the node
	// coalesces deltas over at least this window. 0 = node default.
	MinReportIntervalMs uint32 `protobuf:"varint,1,opt,name=min_report_interval_ms,json=minReportIntervalMs,proto3" json:"min_report_interval_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StreamTrafficRequest) Reset() {
	*x = StreamTrafficRequest{}
	mi := &file_vortex_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTrafficRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTrafficRequest) ProtoMessage() {}

func (x *StreamTrafficRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vortex_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTrafficRequest.ProtoReflect.Descriptor instead.
func (*StreamTrafficRequest) Descriptor() ([]byte, []int) {
	return file_vortex_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *StreamTrafficRequest) GetMinReportIntervalMs() uint32 {
	if x != nil {
		return x.MinReportIntervalMs
	}
	return 0
}

// TrafficDelta is bytes consumed *since the previous delta for this user*.
type TrafficDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Up            uint64                 `protobuf:"varint,2,opt,name=up,proto3" json:"up,omitempty"`
	Down          uint64                 `protobuf:"varint,3,opt,name=down,proto3" json:"down,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficDelta) Reset() {
	*x = TrafficDelta{}
	mi := &file_vortex_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficDelta) ProtoMessage() {}

func (x *TrafficDelta) ProtoReflect() protoreflect.Message {
	mi := &file_vortex_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficDelta.ProtoReflect.Descriptor instead.
func (*TrafficDelta) Descriptor() ([]byte, []int) {
	return file_vortex_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *TrafficDelta) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TrafficDelta) GetUp() uint64 {
	if x != nil {
		return x.Up
	}
	return 0
}

func (x *TrafficDelta) GetDown() uint64 {
	if x != nil {
		return x.Down
	}
	return 0
}

func (x *TrafficDelta) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_vortex_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vortex_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_vortex_v1_node_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    float64                `protobuf:"fixed64,2,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	DiskPercent   float64                `protobuf:"fixed64,3,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	CoreRunning   bool                   `protobuf:"varint,4,opt,name=core_running,json=coreRunning,proto3" json:"core_running,omitempty"`
	Connections   uint32                 `protobuf:"varint,5,opt,name=connections,proto3" json:"connections,omitempty"`
	CoreVersion   string                 `protobuf:"bytes,6,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,7,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_vortex_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vortex_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_vortex_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *HealthResponse) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *HealthResponse) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

func (x *HealthResponse) GetCoreRunning() bool {
	if x != nil {
		return x.CoreRunning
	}
	return false
}

func (x *HealthResponse) GetConnections() uint32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *HealthResponse) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *HealthResponse) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

// Ack is the standard mutating-RPC reply.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // human-readable detail on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_vortex_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_vortex_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_vortex_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_vortex_v1_node_proto protoreflect.FileDescriptor

const file_vortex_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x14vortex/v1/node.proto\x12\tvortex.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x01\n" +
	"\bUserSpec\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"vmess_uuid\x18\x03 \x01(\tR\tvmessUuid\x12\x1d\n" +
	"\n" +
	"vless_uuid\x18\x04 \x01(\tR\tvlessUuid\x12'\n" +
	"\x0ftrojan_password\x18\x05 \x01(\tR\x0etrojanPassword\x12\x1f\n" +
	"\vss_password\x18\x06 \x01(\tR\n" +
	"ssPassword\x12\x1b\n" +
	"\tss_method\x18\a \x01(\tR\bssMethod\x12\x12\n" +
	"\x04flow\x18\b \x01(\tR\x04flow\"\xaf\x01\n" +
	"\vInboundSpec\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06listen\x18\x03 \x01(\tR\x06listen\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12\x18\n" +
	"\anetwork\x18\x05 \x01(\tR\anetwork\x12\x1a\n" +
	"\bsecurity\x18\x06 \x01(\tR\bsecurity\x12\x10\n" +
	"\x03raw\x18\a \x01(\fR\x03raw\"\xb5\x02\n" +
	"\vSyncRequest\x12'\n" +
	"\x04core\x18\x01 \x01(\x0e2\x13.vortex.v1.CoreTypeR\x04core\x12\x1b\n" +
	"\tlog_level\x18\x02 \x01(\tR\blogLevel\x122\n" +
	"\binbounds\x18\x03 \x03(\v2\x16.vortex.v1.InboundSpecR\binbounds\x12T\n" +
	"\x10users_by_inbound\x18\x04 \x03(\v2*.vortex.v1.SyncRequest.UsersByInboundEntryR\x0eusersByInbound\x1aV\n" +
	"\x13UsersByInboundEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.vortex.v1.UserListR\x05value:\x028\x01\"5\n" +
	"\bUserList\x12)\n" +
	"\x05users\x18\x01 \x03(\v2\x13.vortex.v1.UserSpecR\x05users\"Z\n" +
	"\x0eAddUserRequest\x12\x1f\n" +
	"\vinbound_tag\x18\x01 \x01(\tR\n" +
	"inboundTag\x12'\n" +
	"\x04user\x18\x02 \x01(\v2\x13.vortex.v1.UserSpecR\x04user\"M\n" +
	"\x11RemoveUserRequest\x12\x1f\n" +
	"\vinbound_tag\x18\x01 \x01(\tR\n" +
	"inboundTag\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\x14StreamTrafficRequest\x123\n" +
	"\x16min_report_interval_ms\x18\x01 \x01(\rR\x13minReportIntervalMs\"\x85\x01\n" +
	"\fTrafficDelta\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02up\x18\x02 \x01(\x04R\x02up\x12\x12\n" +
	"\x04down\x18\x03 \x01(\x04R\x04down\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x0f\n" +
	"\rHealthRequest\"\x82\x02\n" +
	"\x0eHealthResponse\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x02 \x01(\x01R\n" +
	"memPercent\x12!\n" +
	"\fdisk_percent\x18\x03 \x01(\x01R\vdiskPercent\x12!\n" +
	"\fcore_running\x18\x04 \x01(\bR\vcoreRunning\x12 \n" +
	"\vconnections\x18\x05 \x01(\rR\vconnections\x12!\n" +
	"\fcore_version\x18\x06 \x01(\tR\vcoreVersion\x12#\n" +
	"\ragent_version\x18\a \x01(\tR\fagentVersion\"/\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*P\n" +
	"\bCoreType\x12\x19\n" +
	"\x15CORE_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eCORE_TYPE_XRAY\x10\x01\x12\x15\n" +
	"\x11CORE_TYPE_SINGBOX\x10\x022\xbb\x02\n" +
	"\vNodeService\x12.\n" +
	"\x04Sync\x12\x16.vortex.v1.SyncRequest\x1a\x0e.vortex.v1.Ack\x124\n" +
	"\aAddUser\x12\x19.vortex.v1.AddUserRequest\x1a\x0e.vortex.v1.Ack\x12:\n" +
	"\n" +
	"RemoveUser\x12\x1c.vortex.v1.RemoveUserRequest\x1a\x0e.vortex.v1.Ack\x12K\n" +
	"\rStreamTraffic\x12\x1f.vortex.v1.StreamTrafficRequest\x1a\x17.vortex.v1.TrafficDelta0\x01\x12=\n" +
	"\x06Health\x12\x18.vortex.v1.HealthRequest\x1a\x19.vortex.v1.HealthResponseB=Z;github.com/vortexui/vortexui/internal/transport/genv1;genv1b\x06proto3"

var (
	file_vortex_v1_node_proto_rawDescOnce sync.Once
	file_vortex_v1_node_proto_rawDescData []byte
)

func file_vortex_v1_node_proto_rawDescGZIP() []byte {
	file_vortex_v1_node_proto_rawDescOnce.Do(func() {
		file_vortex_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vortex_v1_node_proto_rawDesc), len(file_vortex_v1_node_proto_rawDesc)))
	})
	return file_vortex_v1_node_proto_rawDescData
}

var file_vortex_v1_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vortex_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_vortex_v1_node_proto_goTypes = []any{
	(CoreType)(0),                 // 0: vortex.v1.CoreType
	(*UserSpec)(nil),              // 1: vortex.v1.UserSpec
	(*InboundSpec)(nil),           // 2: vortex.v1.InboundSpec
	(*SyncRequest)(nil),           // 3: vortex.v1.SyncRequest
	(*UserList)(nil),              // 4: vortex.v1.UserList
	(*AddUserRequest)(nil),        // 5: vortex.v1.AddUserRequest
	(*RemoveUserRequest)(nil),     // 6: vortex.v1.RemoveUserRequest
	(*StreamTrafficRequest)(nil),  // 7: vortex.v1.StreamTrafficRequest
	(*TrafficDelta)(nil),          // 8: vortex.v1.TrafficDelta
	(*HealthRequest)(nil),         // 9: vortex.v1.HealthRequest
	(*HealthResponse)(nil),        // 10: vortex.v1.HealthResponse
	(*Ack)(nil),                   // 11: vortex.v1.Ack
	nil,                           // 12: vortex.v1.SyncRequest.UsersByInboundEntry
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_vortex_v1_node_proto_depIdxs = []int32{
	0,  // 0: vortex.v1.SyncRequest.core:type_name -> vortex.v1.CoreType
	2,  // 1: vortex.v1.SyncRequest.inbounds:type_name -> vortex.v1.InboundSpec
	12, // 2: vortex.v1.SyncRequest.users_by_inbound:type_name -> vortex.v1.SyncRequest.UsersByInboundEntry
	1,  // 3: vortex.v1.UserList.users:type_name -> vortex.v1.UserSpec
	1,  // 4: vortex.v1.AddUserRequest.user:type_name -> vortex.v1.UserSpec
	13, // 5: vortex.v1.TrafficDelta.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 6: vortex.v1.SyncRequest.UsersByInboundEntry.value:type_name -> vortex.v1.UserList
	3,  // 7: vortex.v1.NodeService.Sync:input_type -> vortex.v1.SyncRequest
	5,  // 8: vortex.v1.NodeService.AddUser:input_type -> vortex.v1.AddUserRequest
	6,  // 9: vortex.v1.NodeService.RemoveUser:input_type -> vortex.v1.RemoveUserRequest
	7,  // 10: vortex.v1.NodeService.StreamTraffic:input_type -> vortex.v1.StreamTrafficRequest
	9,  // 11: vortex.v1.NodeService.Health:input_type -> vortex.v1.HealthRequest
	11, // 12: vortex.v1.NodeService.Sync:output_type -> vortex.v1.Ack
	11, // 13: vortex.v1.NodeService.AddUser:output_type -> vortex.v1.Ack
	11, // 14: vortex.v1.NodeService.RemoveUser:output_type -> vortex.v1.Ack
	8,  // 15: vortex.v1.NodeService.StreamTraffic:output_type -> vortex.v1.TrafficDelta
	10, // 16: vortex.v1.NodeService.Health:output_type -> vortex.v1.HealthResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_vortex_v1_node_proto_init() }
func file_vortex_v1_node_proto_init() {
	if File_vortex_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vortex_v1_node_proto_rawDesc), len(file_vortex_v1_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vortex_v1_node_proto_goTypes,
		DependencyIndexes: file_vortex_v1_node_proto_depIdxs,
		EnumInfos:         file_vortex_v1_node_proto_enumTypes,
		MessageInfos:      file_vortex_v1_node_proto_msgTypes,
	}.Build()
	File_vortex_v1_node_proto = out.File
	file_vortex_v1_node_proto_goTypes = nil
	file_vortex_v1_node_proto_depIdxs = nil
}
