package subscription

import (
	"encoding/json"

	"gopkg.in/yaml.v3"
)

// Template allows admins to customize the subscription output by providing a
// base config that the generated proxies are merged into. This is useful for:
// - Adding custom routing rules (direct Iran traffic, block ads, etc.)
// - Setting DNS resolvers
// - Adding custom proxy groups (auto-select, fallback, etc.)
// - Setting experimental features (e.g. sing-box experimental)
//
// The template is stored as JSON in the panel settings and applied per-format
// at render time. Proxies generated by VortexUI are injected into the template's
// proxy list.

// ClashTemplate is a custom base config that proxies are merged into.
type ClashTemplate struct {
	// DNS block merged into the output.
	DNS map[string]any `json:"dns,omitempty" yaml:"dns,omitempty"`
	// Extra proxy groups (appended alongside the auto-generated selector).
	ProxyGroups []map[string]any `json:"proxy-groups,omitempty" yaml:"proxy-groups,omitempty"`
	// Routing rules prepended before the catch-all MATCH rule.
	Rules []string `json:"rules,omitempty" yaml:"rules,omitempty"`
	// Any extra top-level keys (e.g. tun, experimental).
	Extra map[string]any `json:"extra,omitempty" yaml:"-"`
}

// SingboxTemplate is a custom base config for sing-box subscription output.
type SingboxTemplate struct {
	// DNS object merged into output.
	DNS map[string]any `json:"dns,omitempty"`
	// Route rules prepended.
	Route map[string]any `json:"route,omitempty"`
	// Inbounds (e.g. tun inbound for the client).
	Inbounds []map[string]any `json:"inbounds,omitempty"`
	// Any extra top-level keys.
	Experimental map[string]any `json:"experimental,omitempty"`
}

// RenderClashWithTemplate builds a Clash config using a custom template as the
// base, injecting the generated proxies and a selector group.
func RenderClashWithTemplate(proxies []Proxy, title string, tmpl *ClashTemplate) ([]byte, error) {
	var clashProxies []map[string]any
	var names []string
	for _, p := range proxies {
		m := clashProxy(p)
		if m == nil {
			continue
		}
		clashProxies = append(clashProxies, m)
		names = append(names, p.Name)
	}
	if title == "" {
		title = "VortexUI"
	}

	cfg := map[string]any{
		"proxies": clashProxies,
	}

	// Build proxy groups: include template's groups + our selector.
	groups := []map[string]any{{
		"name":    title,
		"type":    "select",
		"proxies": append([]string{"DIRECT"}, names...),
	}}
	if tmpl != nil {
		groups = append(groups, tmpl.ProxyGroups...)
	}
	cfg["proxy-groups"] = groups

	// Rules: template rules + catch-all.
	rules := []string{}
	if tmpl != nil {
		rules = append(rules, tmpl.Rules...)
	}
	rules = append(rules, "MATCH,"+title)
	cfg["rules"] = rules

	// DNS.
	if tmpl != nil && tmpl.DNS != nil {
		cfg["dns"] = tmpl.DNS
	}

	// Extra top-level keys from template.
	if tmpl != nil && tmpl.Extra != nil {
		for k, v := range tmpl.Extra {
			cfg[k] = v
		}
	}

	return yaml.Marshal(cfg)
}

// RenderSingboxWithTemplate builds a sing-box config using a custom template.
func RenderSingboxWithTemplate(proxies []Proxy, title string, tmpl *SingboxTemplate) ([]byte, error) {
	var outbounds []map[string]any
	var tags []string
	for _, p := range proxies {
		o := singboxOutbound(p)
		if o == nil {
			continue
		}
		outbounds = append(outbounds, o)
		tags = append(tags, p.Name)
	}
	if title == "" {
		title = "VortexUI"
	}

	selector := map[string]any{
		"type":      "selector",
		"tag":       title,
		"outbounds": tags,
	}
	direct := map[string]any{"type": "direct", "tag": "direct"}
	all := append([]map[string]any{selector}, outbounds...)
	all = append(all, direct)

	cfg := map[string]any{"outbounds": all}

	if tmpl != nil {
		if tmpl.DNS != nil {
			cfg["dns"] = tmpl.DNS
		}
		if tmpl.Route != nil {
			cfg["route"] = tmpl.Route
		}
		if tmpl.Inbounds != nil {
			cfg["inbounds"] = tmpl.Inbounds
		}
		if tmpl.Experimental != nil {
			cfg["experimental"] = tmpl.Experimental
		}
	}

	return json.MarshalIndent(cfg, "", "  ")
}
