// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSudoAdmins = `-- name: CountSudoAdmins :one
SELECT count(*) FROM admins WHERE sudo = TRUE
`

// CountSudoAdmins guards against locking everyone out by deleting/demoting the
// last full-privilege admin.
func (q *Queries) CountSudoAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSudoAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :exec
INSERT INTO admins (
    id, username, password_hash, sudo, role_id, totp_secret, totp_enabled,
    user_quota, traffic_quota, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateAdminParams struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Sudo         bool
	RoleID       pgtype.UUID
	TotpSecret   string
	TotpEnabled  bool
	UserQuota    int32
	TrafficQuota int64
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) error {
	_, err := q.db.Exec(ctx, createAdmin,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Sudo,
		arg.RoleID,
		arg.TotpSecret,
		arg.TotpEnabled,
		arg.UserQuota,
		arg.TrafficQuota,
		arg.CreatedAt,
	)
	return err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (id, name, permissions) VALUES ($1, $2, $3)
`

type CreateRoleParams struct {
	ID          uuid.UUID
	Name        string
	Permissions []byte
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole, arg.ID, arg.Name, arg.Permissions)
	return err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM admins WHERE id = $1
`

func (q *Queries) DeleteAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdmin, id)
	return err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, username, password_hash, sudo, role_id, totp_secret, totp_enabled, user_quota, traffic_quota, last_login, created_at FROM admins WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Sudo,
		&i.RoleID,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.UserQuota,
		&i.TrafficQuota,
		&i.LastLogin,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, password_hash, sudo, role_id, totp_secret, totp_enabled, user_quota, traffic_quota, last_login, created_at FROM admins WHERE username = $1
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Sudo,
		&i.RoleID,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.UserQuota,
		&i.TrafficQuota,
		&i.LastLogin,
		&i.CreatedAt,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, name, permissions FROM roles WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.Permissions)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, username, password_hash, sudo, role_id, totp_secret, totp_enabled, user_quota, traffic_quota, last_login, created_at FROM admins ORDER BY created_at
`

func (q *Queries) ListAdmins(ctx context.Context) ([]Admin, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Admin{}
	for rows.Next() {
		var i Admin
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Sudo,
			&i.RoleID,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.UserQuota,
			&i.TrafficQuota,
			&i.LastLogin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, permissions FROM roles ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name, &i.Permissions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdmin = `-- name: UpdateAdmin :exec
UPDATE admins SET
    password_hash = $2, sudo = $3, role_id = $4, totp_secret = $5,
    totp_enabled = $6, user_quota = $7, traffic_quota = $8, last_login = $9
WHERE id = $1
`

type UpdateAdminParams struct {
	ID           uuid.UUID
	PasswordHash string
	Sudo         bool
	RoleID       pgtype.UUID
	TotpSecret   string
	TotpEnabled  bool
	UserQuota    int32
	TrafficQuota int64
	LastLogin    pgtype.Timestamptz
}

func (q *Queries) UpdateAdmin(ctx context.Context, arg UpdateAdminParams) error {
	_, err := q.db.Exec(ctx, updateAdmin,
		arg.ID,
		arg.PasswordHash,
		arg.Sudo,
		arg.RoleID,
		arg.TotpSecret,
		arg.TotpEnabled,
		arg.UserQuota,
		arg.TrafficQuota,
		arg.LastLogin,
	)
	return err
}
