// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: api_token.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = $1
`

func (q *Queries) DeleteAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPIToken, id)
	return err
}

const insertAPIToken = `-- name: InsertAPIToken :exec
INSERT INTO api_tokens (id, name, token_hash, admin_id)
VALUES ($1, $2, $3, $4)
`

type InsertAPITokenParams struct {
	ID        uuid.UUID
	Name      string
	TokenHash string
	AdminID   uuid.UUID
}

func (q *Queries) InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) error {
	_, err := q.db.Exec(ctx, insertAPIToken,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.AdminID,
	)
	return err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, name, admin_id, created_at, last_used_at
FROM api_tokens
ORDER BY created_at DESC
`

type ListAPITokensRow struct {
	ID         uuid.UUID
	Name       string
	AdminID    uuid.UUID
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) ListAPITokens(ctx context.Context) ([]ListAPITokensRow, error) {
	rows, err := q.db.Query(ctx, listAPITokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPITokensRow{}
	for rows.Next() {
		var i ListAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AdminID,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAPIToken = `-- name: ResolveAPIToken :one
SELECT t.id, t.admin_id, a.sudo, a.role_id
FROM api_tokens t
JOIN admins a ON a.id = t.admin_id
WHERE t.token_hash = $1
`

type ResolveAPITokenRow struct {
	ID      uuid.UUID
	AdminID uuid.UUID
	Sudo    bool
	RoleID  pgtype.UUID
}

// ResolveAPIToken returns the token row joined with its admin's auth attributes,
// so the middleware can build the same claims a JWT would carry.
func (q *Queries) ResolveAPIToken(ctx context.Context, tokenHash string) (ResolveAPITokenRow, error) {
	row := q.db.QueryRow(ctx, resolveAPIToken, tokenHash)
	var i ResolveAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.Sudo,
		&i.RoleID,
	)
	return i, err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}
