// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balancers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBalancer = `-- name: CreateBalancer :exec
INSERT INTO balancers (
    id, node_id, tag, selectors, strategy, observe, probe_url, probe_interval, enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateBalancerParams struct {
	ID            uuid.UUID
	NodeID        uuid.UUID
	Tag           string
	Selectors     []byte
	Strategy      string
	Observe       bool
	ProbeUrl      string
	ProbeInterval string
	Enabled       bool
}

func (q *Queries) CreateBalancer(ctx context.Context, arg CreateBalancerParams) error {
	_, err := q.db.Exec(ctx, createBalancer,
		arg.ID,
		arg.NodeID,
		arg.Tag,
		arg.Selectors,
		arg.Strategy,
		arg.Observe,
		arg.ProbeUrl,
		arg.ProbeInterval,
		arg.Enabled,
	)
	return err
}

const deleteBalancer = `-- name: DeleteBalancer :exec
DELETE FROM balancers WHERE id = $1
`

func (q *Queries) DeleteBalancer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBalancer, id)
	return err
}

const getBalancerByID = `-- name: GetBalancerByID :one
SELECT id, node_id, tag, selectors, strategy, observe, probe_url, probe_interval, enabled FROM balancers WHERE id = $1
`

func (q *Queries) GetBalancerByID(ctx context.Context, id uuid.UUID) (Balancer, error) {
	row := q.db.QueryRow(ctx, getBalancerByID, id)
	var i Balancer
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Tag,
		&i.Selectors,
		&i.Strategy,
		&i.Observe,
		&i.ProbeUrl,
		&i.ProbeInterval,
		&i.Enabled,
	)
	return i, err
}

const listBalancersByNode = `-- name: ListBalancersByNode :many
SELECT id, node_id, tag, selectors, strategy, observe, probe_url, probe_interval, enabled FROM balancers WHERE node_id = $1 ORDER BY tag
`

func (q *Queries) ListBalancersByNode(ctx context.Context, nodeID uuid.UUID) ([]Balancer, error) {
	rows, err := q.db.Query(ctx, listBalancersByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Balancer{}
	for rows.Next() {
		var i Balancer
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Tag,
			&i.Selectors,
			&i.Strategy,
			&i.Observe,
			&i.ProbeUrl,
			&i.ProbeInterval,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBalancer = `-- name: UpdateBalancer :exec
UPDATE balancers SET
    tag = $2, selectors = $3, strategy = $4, observe = $5,
    probe_url = $6, probe_interval = $7, enabled = $8
WHERE id = $1
`

type UpdateBalancerParams struct {
	ID            uuid.UUID
	Tag           string
	Selectors     []byte
	Strategy      string
	Observe       bool
	ProbeUrl      string
	ProbeInterval string
	Enabled       bool
}

func (q *Queries) UpdateBalancer(ctx context.Context, arg UpdateBalancerParams) error {
	_, err := q.db.Exec(ctx, updateBalancer,
		arg.ID,
		arg.Tag,
		arg.Selectors,
		arg.Strategy,
		arg.Observe,
		arg.ProbeUrl,
		arg.ProbeInterval,
		arg.Enabled,
	)
	return err
}
