// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForWriteTrafficPoints implements pgx.CopyFromSource.
type iteratorForWriteTrafficPoints struct {
	rows                 []WriteTrafficPointsParams
	skippedFirstNextCall bool
}

func (r *iteratorForWriteTrafficPoints) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForWriteTrafficPoints) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Time,
		r.rows[0].UserID,
		r.rows[0].NodeID,
		r.rows[0].Up,
		r.rows[0].Down,
	}, nil
}

func (r iteratorForWriteTrafficPoints) Err() error {
	return nil
}

// WriteTrafficPoints bulk-inserts samples via pgx CopyFrom for high throughput
// under heavy reporting load.
func (q *Queries) WriteTrafficPoints(ctx context.Context, arg []WriteTrafficPointsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"traffic_points"}, []string{"time", "user_id", "node_id", "up", "down"}, &iteratorForWriteTrafficPoints{rows: arg})
}
