// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbounds.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInbound = `-- name: CreateInbound :exec
INSERT INTO inbounds (
    id, node_id, tag, protocol, listen, port, network, security,
    sni, path, host, flow, evasion_profile_id, raw, enabled,
    speed_limit, geo_policy
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
    $16, $17
)
`

type CreateInboundParams struct {
	ID               uuid.UUID
	NodeID           uuid.UUID
	Tag              string
	Protocol         string
	Listen           string
	Port             int32
	Network          string
	Security         string
	Sni              []byte
	Path             string
	Host             []byte
	Flow             string
	EvasionProfileID pgtype.UUID
	Raw              []byte
	Enabled          bool
	SpeedLimit       int64
	GeoPolicy        []byte
}

func (q *Queries) CreateInbound(ctx context.Context, arg CreateInboundParams) error {
	_, err := q.db.Exec(ctx, createInbound,
		arg.ID,
		arg.NodeID,
		arg.Tag,
		arg.Protocol,
		arg.Listen,
		arg.Port,
		arg.Network,
		arg.Security,
		arg.Sni,
		arg.Path,
		arg.Host,
		arg.Flow,
		arg.EvasionProfileID,
		arg.Raw,
		arg.Enabled,
		arg.SpeedLimit,
		arg.GeoPolicy,
	)
	return err
}

const deleteInbound = `-- name: DeleteInbound :exec
DELETE FROM inbounds WHERE id = $1
`

func (q *Queries) DeleteInbound(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInbound, id)
	return err
}

const getInboundByID = `-- name: GetInboundByID :one
SELECT id, node_id, tag, protocol, listen, port, network, security, sni, path, host, flow, evasion_profile_id, raw, enabled, speed_limit, geo_policy FROM inbounds WHERE id = $1
`

func (q *Queries) GetInboundByID(ctx context.Context, id uuid.UUID) (Inbound, error) {
	row := q.db.QueryRow(ctx, getInboundByID, id)
	var i Inbound
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Tag,
		&i.Protocol,
		&i.Listen,
		&i.Port,
		&i.Network,
		&i.Security,
		&i.Sni,
		&i.Path,
		&i.Host,
		&i.Flow,
		&i.EvasionProfileID,
		&i.Raw,
		&i.Enabled,
		&i.SpeedLimit,
		&i.GeoPolicy,
	)
	return i, err
}

const listInboundsByNode = `-- name: ListInboundsByNode :many
SELECT id, node_id, tag, protocol, listen, port, network, security, sni, path, host, flow, evasion_profile_id, raw, enabled, speed_limit, geo_policy FROM inbounds WHERE node_id = $1 ORDER BY tag
`

func (q *Queries) ListInboundsByNode(ctx context.Context, nodeID uuid.UUID) ([]Inbound, error) {
	rows, err := q.db.Query(ctx, listInboundsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inbound{}
	for rows.Next() {
		var i Inbound
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Tag,
			&i.Protocol,
			&i.Listen,
			&i.Port,
			&i.Network,
			&i.Security,
			&i.Sni,
			&i.Path,
			&i.Host,
			&i.Flow,
			&i.EvasionProfileID,
			&i.Raw,
			&i.Enabled,
			&i.SpeedLimit,
			&i.GeoPolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInbound = `-- name: UpdateInbound :exec
UPDATE inbounds SET
    tag = $2, protocol = $3, listen = $4, port = $5, network = $6,
    security = $7, sni = $8, path = $9, host = $10, flow = $11,
    evasion_profile_id = $12, raw = $13, enabled = $14,
    speed_limit = $15, geo_policy = $16
WHERE id = $1
`

type UpdateInboundParams struct {
	ID               uuid.UUID
	Tag              string
	Protocol         string
	Listen           string
	Port             int32
	Network          string
	Security         string
	Sni              []byte
	Path             string
	Host             []byte
	Flow             string
	EvasionProfileID pgtype.UUID
	Raw              []byte
	Enabled          bool
	SpeedLimit       int64
	GeoPolicy        []byte
}

func (q *Queries) UpdateInbound(ctx context.Context, arg UpdateInboundParams) error {
	_, err := q.db.Exec(ctx, updateInbound,
		arg.ID,
		arg.Tag,
		arg.Protocol,
		arg.Listen,
		arg.Port,
		arg.Network,
		arg.Security,
		arg.Sni,
		arg.Path,
		arg.Host,
		arg.Flow,
		arg.EvasionProfileID,
		arg.Raw,
		arg.Enabled,
		arg.SpeedLimit,
		arg.GeoPolicy,
	)
	return err
}
