// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: nodes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNode = `-- name: CreateNode :exec
INSERT INTO nodes (id, name, address, core, status, usage_ratio, endpoint, region, country_code, location_auto, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateNodeParams struct {
	ID           uuid.UUID
	Name         string
	Address      string
	Core         string
	Status       string
	UsageRatio   float64
	Endpoint     string
	Region       string
	CountryCode  string
	LocationAuto bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) error {
	_, err := q.db.Exec(ctx, createNode,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Core,
		arg.Status,
		arg.UsageRatio,
		arg.Endpoint,
		arg.Region,
		arg.CountryCode,
		arg.LocationAuto,
		arg.CreatedAt,
	)
	return err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, name, address, core, status, usage_ratio, endpoint, region, country_code, ping_ms, location_auto, last_seen, cpu_percent, mem_percent, disk_percent, core_running, connections, core_version, agent_version, created_at FROM nodes WHERE id = $1
`

func (q *Queries) GetNodeByID(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Core,
		&i.Status,
		&i.UsageRatio,
		&i.Endpoint,
		&i.Region,
		&i.CountryCode,
		&i.PingMs,
		&i.LocationAuto,
		&i.LastSeen,
		&i.CpuPercent,
		&i.MemPercent,
		&i.DiskPercent,
		&i.CoreRunning,
		&i.Connections,
		&i.CoreVersion,
		&i.AgentVersion,
		&i.CreatedAt,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, address, core, status, usage_ratio, endpoint, region, country_code, ping_ms, location_auto, last_seen, cpu_percent, mem_percent, disk_percent, core_running, connections, core_version, agent_version, created_at FROM nodes ORDER BY created_at
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Core,
			&i.Status,
			&i.UsageRatio,
			&i.Endpoint,
			&i.Region,
			&i.CountryCode,
			&i.PingMs,
			&i.LocationAuto,
			&i.LastSeen,
			&i.CpuPercent,
			&i.MemPercent,
			&i.DiskPercent,
			&i.CoreRunning,
			&i.Connections,
			&i.CoreVersion,
			&i.AgentVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNode = `-- name: UpdateNode :exec
UPDATE nodes SET
    name = $2, address = $3, core = $4, status = $5, usage_ratio = $6, endpoint = $7,
    region = $8, country_code = $9, location_auto = $10
WHERE id = $1
`

type UpdateNodeParams struct {
	ID           uuid.UUID
	Name         string
	Address      string
	Core         string
	Status       string
	UsageRatio   float64
	Endpoint     string
	Region       string
	CountryCode  string
	LocationAuto bool
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) error {
	_, err := q.db.Exec(ctx, updateNode,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Core,
		arg.Status,
		arg.UsageRatio,
		arg.Endpoint,
		arg.Region,
		arg.CountryCode,
		arg.LocationAuto,
	)
	return err
}

const updateNodeHealth = `-- name: UpdateNodeHealth :exec
UPDATE nodes SET
    cpu_percent = $2, mem_percent = $3, disk_percent = $4,
    core_running = $5, connections = $6, core_version = $7, agent_version = $8,
    ping_ms = $9, last_seen = now()
WHERE id = $1
`

type UpdateNodeHealthParams struct {
	ID           uuid.UUID
	CpuPercent   float64
	MemPercent   float64
	DiskPercent  float64
	CoreRunning  bool
	Connections  int32
	CoreVersion  string
	AgentVersion string
	PingMs       int32
}

// UpdateNodeHealth persists the latest heartbeat snapshot from the hub.
func (q *Queries) UpdateNodeHealth(ctx context.Context, arg UpdateNodeHealthParams) error {
	_, err := q.db.Exec(ctx, updateNodeHealth,
		arg.ID,
		arg.CpuPercent,
		arg.MemPercent,
		arg.DiskPercent,
		arg.CoreRunning,
		arg.Connections,
		arg.CoreVersion,
		arg.AgentVersion,
		arg.PingMs,
	)
	return err
}
