// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNode = `-- name: CreateNode :exec
INSERT INTO nodes (id, name, address, core, status, usage_ratio, endpoint, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateNodeParams struct {
	ID         uuid.UUID
	Name       string
	Address    string
	Core       string
	Status     string
	UsageRatio float64
	Endpoint   string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) error {
	_, err := q.db.Exec(ctx, createNode,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Core,
		arg.Status,
		arg.UsageRatio,
		arg.Endpoint,
		arg.CreatedAt,
	)
	return err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, name, address, core, status, usage_ratio, endpoint, last_seen, cpu_percent, mem_percent, disk_percent, core_running, connections, core_version, agent_version, created_at FROM nodes WHERE id = $1
`

func (q *Queries) GetNodeByID(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Core,
		&i.Status,
		&i.UsageRatio,
		&i.Endpoint,
		&i.LastSeen,
		&i.CpuPercent,
		&i.MemPercent,
		&i.DiskPercent,
		&i.CoreRunning,
		&i.Connections,
		&i.CoreVersion,
		&i.AgentVersion,
		&i.CreatedAt,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, address, core, status, usage_ratio, endpoint, last_seen, cpu_percent, mem_percent, disk_percent, core_running, connections, core_version, agent_version, created_at FROM nodes ORDER BY created_at
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Core,
			&i.Status,
			&i.UsageRatio,
			&i.Endpoint,
			&i.LastSeen,
			&i.CpuPercent,
			&i.MemPercent,
			&i.DiskPercent,
			&i.CoreRunning,
			&i.Connections,
			&i.CoreVersion,
			&i.AgentVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNode = `-- name: UpdateNode :exec
UPDATE nodes SET name = $2, address = $3, core = $4, status = $5, usage_ratio = $6, endpoint = $7
WHERE id = $1
`

type UpdateNodeParams struct {
	ID         uuid.UUID
	Name       string
	Address    string
	Core       string
	Status     string
	UsageRatio float64
	Endpoint   string
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) error {
	_, err := q.db.Exec(ctx, updateNode,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Core,
		arg.Status,
		arg.UsageRatio,
		arg.Endpoint,
	)
	return err
}

const updateNodeHealth = `-- name: UpdateNodeHealth :exec
UPDATE nodes SET
    cpu_percent = $2, mem_percent = $3, disk_percent = $4,
    core_running = $5, connections = $6, last_seen = now()
WHERE id = $1
`

type UpdateNodeHealthParams struct {
	ID          uuid.UUID
	CpuPercent  float64
	MemPercent  float64
	DiskPercent float64
	CoreRunning bool
	Connections int32
}

// UpdateNodeHealth persists the latest heartbeat snapshot from the hub.
func (q *Queries) UpdateNodeHealth(ctx context.Context, arg UpdateNodeHealthParams) error {
	_, err := q.db.Exec(ctx, updateNodeHealth,
		arg.ID,
		arg.CpuPercent,
		arg.MemPercent,
		arg.DiskPercent,
		arg.CoreRunning,
		arg.Connections,
	)
	return err
}
