// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbounds.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOutbound = `-- name: CreateOutbound :exec
INSERT INTO outbounds (
    id, node_id, tag, protocol, address, port, uuid, password, username,
    method, flow, network, security, sni, path, host, raw, enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
`

type CreateOutboundParams struct {
	ID       uuid.UUID
	NodeID   uuid.UUID
	Tag      string
	Protocol string
	Address  string
	Port     int32
	Uuid     string
	Password string
	Username string
	Method   string
	Flow     string
	Network  string
	Security string
	Sni      string
	Path     string
	Host     string
	Raw      []byte
	Enabled  bool
}

func (q *Queries) CreateOutbound(ctx context.Context, arg CreateOutboundParams) error {
	_, err := q.db.Exec(ctx, createOutbound,
		arg.ID,
		arg.NodeID,
		arg.Tag,
		arg.Protocol,
		arg.Address,
		arg.Port,
		arg.Uuid,
		arg.Password,
		arg.Username,
		arg.Method,
		arg.Flow,
		arg.Network,
		arg.Security,
		arg.Sni,
		arg.Path,
		arg.Host,
		arg.Raw,
		arg.Enabled,
	)
	return err
}

const deleteOutbound = `-- name: DeleteOutbound :exec
DELETE FROM outbounds WHERE id = $1
`

func (q *Queries) DeleteOutbound(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOutbound, id)
	return err
}

const getOutboundByID = `-- name: GetOutboundByID :one
SELECT id, node_id, tag, protocol, address, port, uuid, password, username, method, flow, network, security, sni, path, host, raw, enabled FROM outbounds WHERE id = $1
`

func (q *Queries) GetOutboundByID(ctx context.Context, id uuid.UUID) (Outbound, error) {
	row := q.db.QueryRow(ctx, getOutboundByID, id)
	var i Outbound
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Tag,
		&i.Protocol,
		&i.Address,
		&i.Port,
		&i.Uuid,
		&i.Password,
		&i.Username,
		&i.Method,
		&i.Flow,
		&i.Network,
		&i.Security,
		&i.Sni,
		&i.Path,
		&i.Host,
		&i.Raw,
		&i.Enabled,
	)
	return i, err
}

const listOutboundsByNode = `-- name: ListOutboundsByNode :many
SELECT id, node_id, tag, protocol, address, port, uuid, password, username, method, flow, network, security, sni, path, host, raw, enabled FROM outbounds WHERE node_id = $1 ORDER BY tag
`

func (q *Queries) ListOutboundsByNode(ctx context.Context, nodeID uuid.UUID) ([]Outbound, error) {
	rows, err := q.db.Query(ctx, listOutboundsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbound{}
	for rows.Next() {
		var i Outbound
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Tag,
			&i.Protocol,
			&i.Address,
			&i.Port,
			&i.Uuid,
			&i.Password,
			&i.Username,
			&i.Method,
			&i.Flow,
			&i.Network,
			&i.Security,
			&i.Sni,
			&i.Path,
			&i.Host,
			&i.Raw,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOutbound = `-- name: UpdateOutbound :exec
UPDATE outbounds SET
    tag = $2, protocol = $3, address = $4, port = $5, uuid = $6, password = $7,
    username = $8, method = $9, flow = $10, network = $11, security = $12,
    sni = $13, path = $14, host = $15, raw = $16, enabled = $17
WHERE id = $1
`

type UpdateOutboundParams struct {
	ID       uuid.UUID
	Tag      string
	Protocol string
	Address  string
	Port     int32
	Uuid     string
	Password string
	Username string
	Method   string
	Flow     string
	Network  string
	Security string
	Sni      string
	Path     string
	Host     string
	Raw      []byte
	Enabled  bool
}

func (q *Queries) UpdateOutbound(ctx context.Context, arg UpdateOutboundParams) error {
	_, err := q.db.Exec(ctx, updateOutbound,
		arg.ID,
		arg.Tag,
		arg.Protocol,
		arg.Address,
		arg.Port,
		arg.Uuid,
		arg.Password,
		arg.Username,
		arg.Method,
		arg.Flow,
		arg.Network,
		arg.Security,
		arg.Sni,
		arg.Path,
		arg.Host,
		arg.Raw,
		arg.Enabled,
	)
	return err
}
