// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routing.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createRoutingRule = `-- name: CreateRoutingRule :exec
INSERT INTO routing_rules (
    id, node_id, priority, name, inbound_tags, domains, ip, port,
    protocols, network, outbound_tag, balancer_tag, enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
`

type CreateRoutingRuleParams struct {
	ID          uuid.UUID
	NodeID      uuid.UUID
	Priority    int32
	Name        string
	InboundTags []byte
	Domains     []byte
	Ip          []byte
	Port        string
	Protocols   []byte
	Network     string
	OutboundTag string
	BalancerTag string
	Enabled     bool
}

func (q *Queries) CreateRoutingRule(ctx context.Context, arg CreateRoutingRuleParams) error {
	_, err := q.db.Exec(ctx, createRoutingRule,
		arg.ID,
		arg.NodeID,
		arg.Priority,
		arg.Name,
		arg.InboundTags,
		arg.Domains,
		arg.Ip,
		arg.Port,
		arg.Protocols,
		arg.Network,
		arg.OutboundTag,
		arg.BalancerTag,
		arg.Enabled,
	)
	return err
}

const deleteRoutingRule = `-- name: DeleteRoutingRule :exec
DELETE FROM routing_rules WHERE id = $1
`

func (q *Queries) DeleteRoutingRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoutingRule, id)
	return err
}

const getRoutingRuleByID = `-- name: GetRoutingRuleByID :one
SELECT id, node_id, priority, name, inbound_tags, domains, ip, port, protocols, network, outbound_tag, balancer_tag, enabled FROM routing_rules WHERE id = $1
`

func (q *Queries) GetRoutingRuleByID(ctx context.Context, id uuid.UUID) (RoutingRule, error) {
	row := q.db.QueryRow(ctx, getRoutingRuleByID, id)
	var i RoutingRule
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Priority,
		&i.Name,
		&i.InboundTags,
		&i.Domains,
		&i.Ip,
		&i.Port,
		&i.Protocols,
		&i.Network,
		&i.OutboundTag,
		&i.BalancerTag,
		&i.Enabled,
	)
	return i, err
}

const listRoutingRulesByNode = `-- name: ListRoutingRulesByNode :many
SELECT id, node_id, priority, name, inbound_tags, domains, ip, port, protocols, network, outbound_tag, balancer_tag, enabled FROM routing_rules WHERE node_id = $1 ORDER BY priority, id
`

func (q *Queries) ListRoutingRulesByNode(ctx context.Context, nodeID uuid.UUID) ([]RoutingRule, error) {
	rows, err := q.db.Query(ctx, listRoutingRulesByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoutingRule{}
	for rows.Next() {
		var i RoutingRule
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Priority,
			&i.Name,
			&i.InboundTags,
			&i.Domains,
			&i.Ip,
			&i.Port,
			&i.Protocols,
			&i.Network,
			&i.OutboundTag,
			&i.BalancerTag,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoutingRule = `-- name: UpdateRoutingRule :exec
UPDATE routing_rules SET
    priority = $2, name = $3, inbound_tags = $4, domains = $5, ip = $6,
    port = $7, protocols = $8, network = $9, outbound_tag = $10,
    balancer_tag = $11, enabled = $12
WHERE id = $1
`

type UpdateRoutingRuleParams struct {
	ID          uuid.UUID
	Priority    int32
	Name        string
	InboundTags []byte
	Domains     []byte
	Ip          []byte
	Port        string
	Protocols   []byte
	Network     string
	OutboundTag string
	BalancerTag string
	Enabled     bool
}

func (q *Queries) UpdateRoutingRule(ctx context.Context, arg UpdateRoutingRuleParams) error {
	_, err := q.db.Exec(ctx, updateRoutingRule,
		arg.ID,
		arg.Priority,
		arg.Name,
		arg.InboundTags,
		arg.Domains,
		arg.Ip,
		arg.Port,
		arg.Protocols,
		arg.Network,
		arg.OutboundTag,
		arg.BalancerTag,
		arg.Enabled,
	)
	return err
}
