// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: traffic.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const totalSeries = `-- name: TotalSeries :many
SELECT
    date_bin($1::interval, time, TIMESTAMPTZ '2000-01-01')::timestamptz AS bucket,
    sum(up)::bigint   AS up,
    sum(down)::bigint AS down
FROM traffic_points
WHERE time >= $2
  AND time <  $3
GROUP BY bucket
ORDER BY bucket
`

type TotalSeriesParams struct {
	Bucket pgtype.Interval
	FromTs pgtype.Timestamptz
	ToTs   pgtype.Timestamptz
}

type TotalSeriesRow struct {
	Bucket pgtype.Timestamptz
	Up     int64
	Down   int64
}

// TotalSeries buckets fleet-wide traffic (all users, all nodes) over a time
// range. Powers the live dashboard throughput chart.
func (q *Queries) TotalSeries(ctx context.Context, arg TotalSeriesParams) ([]TotalSeriesRow, error) {
	rows, err := q.db.Query(ctx, totalSeries, arg.Bucket, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TotalSeriesRow{}
	for rows.Next() {
		var i TotalSeriesRow
		if err := rows.Scan(&i.Bucket, &i.Up, &i.Down); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageSeries = `-- name: UsageSeries :many
SELECT
    date_bin($1::interval, time, TIMESTAMPTZ '2000-01-01')::timestamptz AS bucket,
    sum(up)::bigint   AS up,
    sum(down)::bigint AS down
FROM traffic_points
WHERE user_id = $2
  AND time >= $3
  AND time <  $4
GROUP BY bucket
ORDER BY bucket
`

type UsageSeriesParams struct {
	Bucket pgtype.Interval
	UserID uuid.UUID
	FromTs pgtype.Timestamptz
	ToTs   pgtype.Timestamptz
}

type UsageSeriesRow struct {
	Bucket pgtype.Timestamptz
	Up     int64
	Down   int64
}

// UsageSeries buckets a user's traffic over a time range. date_bin (Postgres 14+,
// standard — not a TimescaleDB extension function) groups rows into fixed-width
// intervals so this works even without the extension installed.
func (q *Queries) UsageSeries(ctx context.Context, arg UsageSeriesParams) ([]UsageSeriesRow, error) {
	rows, err := q.db.Query(ctx, usageSeries,
		arg.Bucket,
		arg.UserID,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageSeriesRow{}
	for rows.Next() {
		var i UsageSeriesRow
		if err := rows.Scan(&i.Bucket, &i.Up, &i.Down); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type WriteTrafficPointsParams struct {
	Time   pgtype.Timestamptz
	UserID uuid.UUID
	NodeID uuid.UUID
	Up     int64
	Down   int64
}
