// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addUsedTraffic = `-- name: AddUsedTraffic :exec
UPDATE users SET used_traffic = used_traffic + $2, updated_at = now()
WHERE id = $1
`

type AddUsedTrafficParams struct {
	ID          uuid.UUID
	UsedTraffic int64
}

// AddUsedTraffic atomically folds a traffic delta into the aggregate counter in
// one statement, so concurrent reports from multiple nodes never race.
func (q *Queries) AddUsedTraffic(ctx context.Context, arg AddUsedTrafficParams) error {
	_, err := q.db.Exec(ctx, addUsedTraffic, arg.ID, arg.UsedTraffic)
	return err
}

const addUsedTrafficBatch = `-- name: AddUsedTrafficBatch :exec
UPDATE users u
SET used_traffic = u.used_traffic + d.delta, updated_at = now()
FROM (
    SELECT unnest($1::uuid[]) AS id, unnest($2::bigint[]) AS delta
) d
WHERE u.id = d.id
`

type AddUsedTrafficBatchParams struct {
	Ids    []uuid.UUID
	Deltas []int64
}

// AddUsedTrafficBatch folds many per-user deltas in ONE statement (parallel
// id/delta arrays), so the stats flush is a single round-trip regardless of how
// many users had traffic in the window.
func (q *Queries) AddUsedTrafficBatch(ctx context.Context, arg AddUsedTrafficBatchParams) error {
	_, err := q.db.Exec(ctx, addUsedTrafficBatch, arg.Ids, arg.Deltas)
	return err
}

const addUserInbound = `-- name: AddUserInbound :exec
INSERT INTO user_inbounds (user_id, inbound_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserInboundParams struct {
	UserID    uuid.UUID
	InboundID uuid.UUID
}

func (q *Queries) AddUserInbound(ctx context.Context, arg AddUserInboundParams) error {
	_, err := q.db.Exec(ctx, addUserInbound, arg.UserID, arg.InboundID)
	return err
}

const adminUserStats = `-- name: AdminUserStats :one
SELECT
    count(*)::bigint AS user_count,
    COALESCE(SUM(used_traffic), 0)::bigint AS traffic_used,
    COALESCE(SUM(data_limit), 0)::bigint AS traffic_allocated
FROM users
WHERE admin_id = $1
`

type AdminUserStatsRow struct {
	UserCount        int64
	TrafficUsed      int64
	TrafficAllocated int64
}

func (q *Queries) AdminUserStats(ctx context.Context, adminID pgtype.UUID) (AdminUserStatsRow, error) {
	row := q.db.QueryRow(ctx, adminUserStats, adminID)
	var i AdminUserStatsRow
	err := row.Scan(&i.UserCount, &i.TrafficUsed, &i.TrafficAllocated)
	return i, err
}

const clearUserInbounds = `-- name: ClearUserInbounds :exec
DELETE FROM user_inbounds WHERE user_id = $1
`

func (q *Queries) ClearUserInbounds(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserInbounds, userID)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
WHERE ($1::text = '' OR username ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR status = $2)
  AND ($3::uuid IS NULL OR admin_id = $3)
`

type CountUsersParams struct {
	Search  string
	Status  string
	AdminID pgtype.UUID
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Search, arg.Status, arg.AdminID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id, username, status, note, data_limit, used_traffic, expire_at,
    on_hold_expire, reset_strategy, last_reset, device_limit, allowed_hwids,
    vmess_uuid, vless_uuid, trojan_pass, ss_password, ss_method, sub_token,
    admin_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18, $19, $20, $21
)
`

type CreateUserParams struct {
	ID            uuid.UUID
	Username      string
	Status        string
	Note          string
	DataLimit     int64
	UsedTraffic   int64
	ExpireAt      pgtype.Timestamptz
	OnHoldExpire  pgtype.Int8
	ResetStrategy string
	LastReset     pgtype.Timestamptz
	DeviceLimit   int32
	AllowedHwids  []byte
	VmessUuid     uuid.UUID
	VlessUuid     uuid.UUID
	TrojanPass    string
	SsPassword    string
	SsMethod      string
	SubToken      string
	AdminID       pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Status,
		arg.Note,
		arg.DataLimit,
		arg.UsedTraffic,
		arg.ExpireAt,
		arg.OnHoldExpire,
		arg.ResetStrategy,
		arg.LastReset,
		arg.DeviceLimit,
		arg.AllowedHwids,
		arg.VmessUuid,
		arg.VlessUuid,
		arg.TrojanPass,
		arg.SsPassword,
		arg.SsMethod,
		arg.SubToken,
		arg.AdminID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, status, note, data_limit, used_traffic, expire_at, on_hold_expire, reset_strategy, last_reset, device_limit, allowed_hwids, vmess_uuid, vless_uuid, trojan_pass, ss_password, ss_method, sub_token, routing_pack_id, admin_id, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Status,
		&i.Note,
		&i.DataLimit,
		&i.UsedTraffic,
		&i.ExpireAt,
		&i.OnHoldExpire,
		&i.ResetStrategy,
		&i.LastReset,
		&i.DeviceLimit,
		&i.AllowedHwids,
		&i.VmessUuid,
		&i.VlessUuid,
		&i.TrojanPass,
		&i.SsPassword,
		&i.SsMethod,
		&i.SubToken,
		&i.RoutingPackID,
		&i.AdminID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBySubToken = `-- name: GetUserBySubToken :one
SELECT id, username, status, note, data_limit, used_traffic, expire_at, on_hold_expire, reset_strategy, last_reset, device_limit, allowed_hwids, vmess_uuid, vless_uuid, trojan_pass, ss_password, ss_method, sub_token, routing_pack_id, admin_id, created_at, updated_at FROM users WHERE sub_token = $1
`

func (q *Queries) GetUserBySubToken(ctx context.Context, subToken string) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySubToken, subToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Status,
		&i.Note,
		&i.DataLimit,
		&i.UsedTraffic,
		&i.ExpireAt,
		&i.OnHoldExpire,
		&i.ResetStrategy,
		&i.LastReset,
		&i.DeviceLimit,
		&i.AllowedHwids,
		&i.VmessUuid,
		&i.VlessUuid,
		&i.TrojanPass,
		&i.SsPassword,
		&i.SsMethod,
		&i.SubToken,
		&i.RoutingPackID,
		&i.AdminID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const inboundsForUser = `-- name: InboundsForUser :many
SELECT i.id, i.node_id, i.tag, i.protocol, i.listen, i.port, i.network, i.security, i.sni, i.path, i.host, i.flow, i.evasion_profile_id, i.raw, i.enabled, i.speed_limit, i.geo_policy FROM inbounds i
JOIN user_inbounds ui ON ui.inbound_id = i.id
WHERE ui.user_id = $1
`

func (q *Queries) InboundsForUser(ctx context.Context, userID uuid.UUID) ([]Inbound, error) {
	rows, err := q.db.Query(ctx, inboundsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inbound{}
	for rows.Next() {
		var i Inbound
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Tag,
			&i.Protocol,
			&i.Listen,
			&i.Port,
			&i.Network,
			&i.Security,
			&i.Sni,
			&i.Path,
			&i.Host,
			&i.Flow,
			&i.EvasionProfileID,
			&i.Raw,
			&i.Enabled,
			&i.SpeedLimit,
			&i.GeoPolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, status, note, data_limit, used_traffic, expire_at, on_hold_expire, reset_strategy, last_reset, device_limit, allowed_hwids, vmess_uuid, vless_uuid, trojan_pass, ss_password, ss_method, sub_token, routing_pack_id, admin_id, created_at, updated_at FROM users
WHERE ($1::text = '' OR username ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR status = $2)
  AND ($3::uuid IS NULL OR admin_id = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListUsersParams struct {
	Search  string
	Status  string
	AdminID pgtype.UUID
	Off     int32
	Lim     int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.Status,
		arg.AdminID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Status,
			&i.Note,
			&i.DataLimit,
			&i.UsedTraffic,
			&i.ExpireAt,
			&i.OnHoldExpire,
			&i.ResetStrategy,
			&i.LastReset,
			&i.DeviceLimit,
			&i.AllowedHwids,
			&i.VmessUuid,
			&i.VlessUuid,
			&i.TrojanPass,
			&i.SsPassword,
			&i.SsMethod,
			&i.SubToken,
			&i.RoutingPackID,
			&i.AdminID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserInbound = `-- name: RemoveUserInbound :exec
DELETE FROM user_inbounds WHERE user_id = $1 AND inbound_id = $2
`

type RemoveUserInboundParams struct {
	UserID    uuid.UUID
	InboundID uuid.UUID
}

func (q *Queries) RemoveUserInbound(ctx context.Context, arg RemoveUserInboundParams) error {
	_, err := q.db.Exec(ctx, removeUserInbound, arg.UserID, arg.InboundID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
    username = $2, status = $3, note = $4, data_limit = $5, used_traffic = $6,
    expire_at = $7, on_hold_expire = $8, reset_strategy = $9, last_reset = $10,
    device_limit = $11, allowed_hwids = $12, trojan_pass = $13,
    ss_password = $14, ss_method = $15, updated_at = now()
WHERE id = $1
`

type UpdateUserParams struct {
	ID            uuid.UUID
	Username      string
	Status        string
	Note          string
	DataLimit     int64
	UsedTraffic   int64
	ExpireAt      pgtype.Timestamptz
	OnHoldExpire  pgtype.Int8
	ResetStrategy string
	LastReset     pgtype.Timestamptz
	DeviceLimit   int32
	AllowedHwids  []byte
	TrojanPass    string
	SsPassword    string
	SsMethod      string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Status,
		arg.Note,
		arg.DataLimit,
		arg.UsedTraffic,
		arg.ExpireAt,
		arg.OnHoldExpire,
		arg.ResetStrategy,
		arg.LastReset,
		arg.DeviceLimit,
		arg.AllowedHwids,
		arg.TrojanPass,
		arg.SsPassword,
		arg.SsMethod,
	)
	return err
}

const userStats = `-- name: UserStats :many
SELECT status, COUNT(*)::bigint AS count, COALESCE(SUM(used_traffic), 0)::bigint AS used_traffic
FROM users
GROUP BY status
`

type UserStatsRow struct {
	Status      string
	Count       int64
	UsedTraffic int64
}

// UserStats aggregates user counts and total used traffic per status, powering
// the dashboard overview in a single round-trip.
func (q *Queries) UserStats(ctx context.Context) ([]UserStatsRow, error) {
	rows, err := q.db.Query(ctx, userStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserStatsRow{}
	for rows.Next() {
		var i UserStatsRow
		if err := rows.Scan(&i.Status, &i.Count, &i.UsedTraffic); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usersByNode = `-- name: UsersByNode :many
SELECT i.tag, u.id, u.username, u.status, u.note, u.data_limit, u.used_traffic, u.expire_at, u.on_hold_expire, u.reset_strategy, u.last_reset, u.device_limit, u.allowed_hwids, u.vmess_uuid, u.vless_uuid, u.trojan_pass, u.ss_password, u.ss_method, u.sub_token, u.routing_pack_id, u.admin_id, u.created_at, u.updated_at
FROM inbounds i
JOIN user_inbounds ui ON ui.inbound_id = i.id
JOIN users u ON u.id = ui.user_id
WHERE i.node_id = $1 AND i.enabled = TRUE
`

type UsersByNodeRow struct {
	Tag  string
	User User
}

// UsersByNode returns every (inbound tag, user) pair on a node's enabled
// inbounds, the read model used to assemble a node's full desired core config.
func (q *Queries) UsersByNode(ctx context.Context, nodeID uuid.UUID) ([]UsersByNodeRow, error) {
	rows, err := q.db.Query(ctx, usersByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsersByNodeRow{}
	for rows.Next() {
		var i UsersByNodeRow
		if err := rows.Scan(
			&i.Tag,
			&i.User.ID,
			&i.User.Username,
			&i.User.Status,
			&i.User.Note,
			&i.User.DataLimit,
			&i.User.UsedTraffic,
			&i.User.ExpireAt,
			&i.User.OnHoldExpire,
			&i.User.ResetStrategy,
			&i.User.LastReset,
			&i.User.DeviceLimit,
			&i.User.AllowedHwids,
			&i.User.VmessUuid,
			&i.User.VlessUuid,
			&i.User.TrojanPass,
			&i.User.SsPassword,
			&i.User.SsMethod,
			&i.User.SubToken,
			&i.User.RoutingPackID,
			&i.User.AdminID,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usersExpiringSoon = `-- name: UsersExpiringSoon :many
SELECT id, username, status, note, data_limit, used_traffic, expire_at, on_hold_expire, reset_strategy, last_reset, device_limit, allowed_hwids, vmess_uuid, vless_uuid, trojan_pass, ss_password, ss_method, sub_token, routing_pack_id, admin_id, created_at, updated_at FROM users
WHERE status = 'active' AND expire_at IS NOT NULL AND expire_at <= $1 AND expire_at > now()
`

func (q *Queries) UsersExpiringSoon(ctx context.Context, expireAt pgtype.Timestamptz) ([]User, error) {
	rows, err := q.db.Query(ctx, usersExpiringSoon, expireAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Status,
			&i.Note,
			&i.DataLimit,
			&i.UsedTraffic,
			&i.ExpireAt,
			&i.OnHoldExpire,
			&i.ResetStrategy,
			&i.LastReset,
			&i.DeviceLimit,
			&i.AllowedHwids,
			&i.VmessUuid,
			&i.VlessUuid,
			&i.TrojanPass,
			&i.SsPassword,
			&i.SsMethod,
			&i.SubToken,
			&i.RoutingPackID,
			&i.AdminID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usersToLimit = `-- name: UsersToLimit :many
SELECT id, username, status, note, data_limit, used_traffic, expire_at, on_hold_expire, reset_strategy, last_reset, device_limit, allowed_hwids, vmess_uuid, vless_uuid, trojan_pass, ss_password, ss_method, sub_token, routing_pack_id, admin_id, created_at, updated_at FROM users
WHERE status = 'active'
  AND (
    (data_limit > 0 AND used_traffic >= data_limit)
    OR (expire_at IS NOT NULL AND expire_at <= now())
  )
`

// UsersToLimit returns active users who have crossed their data cap or expiry,
// so the enforcement loop can disable+de-provision exactly those (not a full
// table scan). now() is evaluated server-side to avoid clock skew.
func (q *Queries) UsersToLimit(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, usersToLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Status,
			&i.Note,
			&i.DataLimit,
			&i.UsedTraffic,
			&i.ExpireAt,
			&i.OnHoldExpire,
			&i.ResetStrategy,
			&i.LastReset,
			&i.DeviceLimit,
			&i.AllowedHwids,
			&i.VmessUuid,
			&i.VlessUuid,
			&i.TrojanPass,
			&i.SsPassword,
			&i.SsMethod,
			&i.SubToken,
			&i.RoutingPackID,
			&i.AdminID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usersToReset = `-- name: UsersToReset :many
SELECT id, username, status, note, data_limit, used_traffic, expire_at, on_hold_expire, reset_strategy, last_reset, device_limit, allowed_hwids, vmess_uuid, vless_uuid, trojan_pass, ss_password, ss_method, sub_token, routing_pack_id, admin_id, created_at, updated_at FROM users
WHERE reset_strategy <> 'no_reset'
  AND (
    last_reset IS NULL
    OR (reset_strategy = 'daily'   AND last_reset <= now() - interval '1 day')
    OR (reset_strategy = 'weekly'  AND last_reset <= now() - interval '7 days')
    OR (reset_strategy = 'monthly' AND last_reset <= now() - interval '1 month')
  )
`

// UsersToReset returns users whose periodic traffic reset is due, computing the
// per-strategy window in SQL so the loop only touches users that need it.
func (q *Queries) UsersToReset(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, usersToReset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Status,
			&i.Note,
			&i.DataLimit,
			&i.UsedTraffic,
			&i.ExpireAt,
			&i.OnHoldExpire,
			&i.ResetStrategy,
			&i.LastReset,
			&i.DeviceLimit,
			&i.AllowedHwids,
			&i.VmessUuid,
			&i.VlessUuid,
			&i.TrojanPass,
			&i.SsPassword,
			&i.SsMethod,
			&i.SubToken,
			&i.RoutingPackID,
			&i.AdminID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
